version: '{build}'
skip_tags: true
environment:
  MAVEN_VERSION: 3.5.0
  matrix:
    - JAVA_HOME: C:\Program Files\Java\jdk1.8.0
install:
  - ps: |
      Add-Type -AssemblyName System.IO.Compression.FileSystem
      if (!(Test-Path -Path "C:\maven" )) {
        Write-Host "Downloading Maven $env:MAVEN_VERSION"
        (new-object System.Net.WebClient).DownloadFile("https://repo1.maven.org/maven2/org/apache/maven/apache-maven/$env:MAVEN_VERSION/apache-maven-$env:MAVEN_VERSION-bin.zip", 'C:\maven-bin.zip')
        [System.IO.Compression.ZipFile]::ExtractToDirectory("C:\maven-bin.zip", "C:\maven")
      }
  - cmd: SET M2_HOME=C:\maven\apache-maven-%MAVEN_VERSION%
  # Prepend Java entry, remove Ruby entry (C:\Ruby193\bin;) from PATH
  - cmd: SET PATH=%M2_HOME%\bin;%JAVA_HOME%\bin;%PATH:C:\Ruby193\bin;=%;
  - cmd: mvn --version
  - cmd: java -version
  - ps: |
      Add-Type -AssemblyName System.IO.Compression.FileSystem
      if (!(Test-Path -Path "C:\uctags" )) {
        Write-Host "Downloading Universal Ctags"
        # Project has not had a versioned release so far, but looks like these nightly builds are retained for at least a year
        # so picked an arbitrary version to use for tests
        (new-object System.Net.WebClient).DownloadFile("https://github.com/universal-ctags/ctags-win32/releases/download/2018-09-29%2Fd0807887/ctags-2018-09-29_d0807887-x86.zip", 'C:\uctags-bin.zip')
        [System.IO.Compression.ZipFile]::ExtractToDirectory("C:\uctags-bin.zip", "C:\uctags")
      }
build_script:
    - mvn -B -V -Dorg.opengrok.indexer.analysis.Ctags=c:\uctags\ctags.exe clean verify
cache:
  - C:\maven\ -> appveyor.yml
  - C:\Users\appveyor\.m2\ -> pom.xml
